export const SPACELIST = [
  {
    id: 1,
    name: "게임 파티룸 플레이앤 삼성역점",
    location: "삼성동",
    people: "3",
    review: "4.2",
    reviewTotal: "103",
    link: "",
  },
  {
    id: 2,
    name: "게임 파티룸 플레이앤 삼성역점",
    location: "삼성동",
    people: "3",
    review: "4.2",
    reviewTotal: "103",
    link: "",
  },
  {
    id: 3,
    name: "게임 파티룸 플레이앤 삼성역점",
    location: "삼성동",
    people: "3",
    review: "4.2",
    reviewTotal: "103",
    link: "",
  },
  {
    id: 4,
    name: "게임 파티룸 플레이앤 삼성역점",
    location: "삼성동",
    people: "3",
    review: "4.2",
    reviewTotal: "103",
    link: "",
  },
  {
    id: 5,
    name: "게임 파티룸 플레이앤 삼성역점",
    location: "삼성동",
    people: "3",
    review: "4.2",
    reviewTotal: "103",
    link: "",
  },
  {
    id: 6,
    name: "게임 파티룸 플레이앤 삼성역점",
    location: "삼성동",
    people: "3",
    review: "4.2",
    reviewTotal: "103",
    link: "",
  },
];
